### ISSUE TITLE
Bug in read_params

### ISSUE THREAD

**Issue by manodeep** [arhstevens/DarkSage#2]
Trying to run the new version for importing into TAO, I kept running into an error `Tag "ot" not allowed or multiple defined`. Turns out that the line in the parameter file was too big for compared to the amount of buffer being read-in. 

Simple fix is to change `200` to `400` in [this line](https://github.com/arhstevens/DarkSage/blob/astevens-disc/code/core_read_parameter_file.c#L285). The buffer variable is allocated to be 400 bytes, so it should be safe to pass 400 into `fgets` (`fgets` itself will reserve one byte for the NULL terminator -- `\0`, i.e., at most 399 bytes of useful data can be read in from the line)

**Comment by arhstevens** [comment]
Now updated!
